// <auto-generated />
using Inventario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Electrónica",
                            Nombre = "Laptop",
                            Precio = 999.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Electrónica",
                            Nombre = "Smartphone",
                            Precio = 499.99m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Muebles",
                            Nombre = "Mesa de Oficina",
                            Precio = 199.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Muebles",
                            Nombre = "Silla Ergonómica",
                            Precio = 149.99m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Electrónica",
                            Nombre = "Mouse Ergonómico",
                            Precio = 700.00m,
                            Stock = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
